Bounce improvements
TheDuckCow/MCprep pull request #312
Opened 2022-06-29 16:03 UTC by StandingPadAnimations

These changes are being added to the optimizer (once I finish them up):
* Volumetric stepping rate modification 
* Automatic scrambling distance optimization
* Better glossy and transmissive optimization (in a different way compared to how I planned on doing it)

2022-06-29 17:37 UTC, StandingPadAnimations commented
The improvements are pretty much finished. All that is needed is a code review before merging

2022-07-02 01:42 UTC, StandingPadAnimations commented
@TheDuckCow just requesting a code review before merging

2022-07-02 04:37 UTC, TheDuckCow commented
Thanks for flagging - taking a look but might not finish in one sitting. Will do by (my) tomorrow morning latest.

2022-07-02 04:54 UTC, TheDuckCow requested changes
Mostly minor changes (other than variable renaming to follow snake_case, but I'm happy to do that post merge myself since it's nit picky)

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +MIN_SCRAMBLING_MULTIPLIER = 0.35
For these any any other above constants, if you have any one-line comment to add to why these values are set, would be greatly helpful.

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +		UseScrambling = scn_props.scrambling_unsafe
nit about variable naming: `uses_scrambling` here and below (there's some variable names from your prior merge too that I didn't get to updating)

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +				print("Disabling Automatic Scrambling Distance as it is useless for CPU rendering!")
Does it harm rendering keeping it on? Something to consider is someone who works on their file in one machine, but then renders on another (I do this often). Obviously they won't get all the best optimizations unless they ran optimize again on the other machine, but not always feasible for a render farm. If there are some settings that have no harm to CPU but positively affect GPU, I'd just always enable it.

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +						node.bl_idname == "ShaderNodeVolumeAbsorption" or \
I'd rephase this to be easier to read, right now it's hard to see where the if ends (plus it's not advised to need to use `\` for line continuance, and multi line if's are just icky in general imo):

```python
vol_nodes = [
    "ShaderNodeVolumeScatter",
    "ShaderNodeVolumeAbsorption",
    "ShaderNodeVolumePrincipled"
]
if node.bl_idname in vol_nodes:
    ...
```

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +						node.bl_idname == "ShaderNodeVolumePrincipled":
Am I reading this right, is this changing the type of the node? Might this have other odd side effects?

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +								Glossy = Glossy - 1 if Glossy > 1 else Glossy
nit alt phrasing idea that is easier to read (also note the renaming to lower case... I can also make that change post merge if you don't want to spend time renaming vars):

```
glossy -= 1 if glossy > 1 else 0
```

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/optimize_scene.py
> +						density_socket = node.inputs["Density"] # Grab the density
Let's move this indented level and below into another function if possible, it's getting way too indented here.

2022-07-02 04:54 UTC, TheDuckCow commented on README.md
> +### Cycles Optimizer
Thanks for adding docs!!

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/util.py
> +def max_bv(version, *, up_to=None):
Per comment in other PR, isn't this about the equiv to inverting the output of min_bv? I'd rather not add a new function.

2022-07-02 04:54 UTC, TheDuckCow commented on MCprep_addon/util.py
> +def min_bv(version, *, above=None):
Would rename `above=None` to be `inclusive=False` and inver the if/else below.

2022-07-02 18:09 UTC, StandingPadAnimations commented
Everything should be improved now. I'll merge this PR now

2022-07-02 18:12 UTC, merged