Desaturation fix
TheDuckCow/MCprep pull request #374
Opened 2023-02-21 18:41 UTC by StandingPadAnimations

As mentioned in https://github.com/TheDuckCow/MCprep/issues/368#issuecomment-1438924696, the desaturation bug that's been recently plaguing MCprep for a while is caused by using an incorrect index. This PR should hopefully fix it (fingers crossed, I haven't tested it yet)

2023-02-22 07:03 UTC, TheDuckCow requested changes
Good fix to make, spot check the value and consider using the more generic selector

2023-02-22 07:03 UTC, TheDuckCow commented on MCprep_addon/materials/generate.py
> +			sat_node.inputs[6].default_value = desat_color
On a spot check, shouldn't this be index 7? Index 6 is actually the "line in", ie the connected texture, while 7 would be the assignment of the actual color to apply.

```suggestion
			sat_node.inputs[7].default_value = desat_color
```

That being said, should we also consider using this new infra for version agnostic node selection? tbh i actually find your current code change easier to follow... but I guess if we want to be consistent we'd do something like below (95% sure this isn't quite right):

```
sat_node_in = get_node_socket(sat_node)
...
sat_node.inputs[sat_node_in[2]
```

2023-02-23 00:22 UTC, StandingPadAnimations commented
Made the necessary change. `get_node_socket` returns a list, so I think the code was meant to access index 2 of that list (which would indeed be index 7 of the Mix node)

2023-03-06 14:07 UTC, TheDuckCow approved these changes
Good to go - please merge at your earliest convenience!

2023-03-06 15:29 UTC, merged